Repository GitFlow-Exercise/MongoAI-web, pull requests merged in 2025-05, with the labels that each got.

#25 feat/로그인+회원가입 화면 제작 및 기능 구현
  lib/auth/sign_in/controller/sign_in_action.dart
  lib/auth/sign_in/controller/sign_in_state.dart
  lib/auth/sign_in/controller/sign_in_view_model.dart
  lib/auth/sign_in/screen/sign_in_screen.dart
  lib/auth/sign_in/screen/sign_in_screen_root.dart
  lib/auth/sign_up/controller/sign_up_action.dart
  lib/auth/sign_up/controller/sign_up_state.dart
  lib/auth/sign_up/controller/sign_up_view_model.dart
  lib/auth/sign_up/screen/password_sign_up_screen.dart
  lib/auth/sign_up/screen/sign_up_complete_screen.dart
  lib/auth/sign_up/screen/sign_up_screen.dart
  lib/auth/sign_up/screen/sign_up_screen_root.dart
  lib/core/component/base_text_field.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/main.dart
Labels: feat

#27 feat/ Open AI 통신 기능 구현
  lib/core/constants/ai_constant.dart
  lib/core/constants/prompt.dart
  lib/core/converter/input_converter.dart
  lib/core/di/providers.dart
  lib/core/exception/app_exception.dart
  lib/core/routing/router.dart
  lib/create/data/data_source/open_ai_data_source.dart
  lib/create/data/data_source/open_ai_data_source_impl.dart
  lib/create/data/dto/request/input_content_dto.dart
  lib/create/data/dto/request/message_input_dto.dart
  lib/create/data/dto/request/open_ai_body_dto.dart
  lib/create/data/dto/response/open_ai_response_content_dto.dart
  lib/create/data/dto/response/open_ai_response_dto.dart
  lib/create/data/dto/response/open_ai_response_output_dto.dart
  lib/create/data/mapper/request/input_content_mapper.dart
  lib/create/data/mapper/request/message_input_mapper.dart
  lib/create/data/mapper/request/open_ai_body_mapper.dart
  lib/create/data/mapper/response/open_ai_response_content_mapper.dart
  lib/create/data/mapper/response/open_ai_response_mapper.dart
  lib/create/data/mapper/response/open_ai_response_output_mapper.dart
  lib/create/data/repository/open_ai_repository_impl.dart
  lib/create/domain/model/request/input_content.dart
  lib/create/domain/model/request/message_input.dart
  lib/create/domain/model/request/open_ai_body.dart
  lib/create/domain/model/response/open_ai_response.dart
  lib/create/domain/model/response/open_ai_response_content.dart
  lib/create/domain/model/response/open_ai_response_output.dart
  lib/create/domain/repository/open_ai_repository.dart
  lib/create/domain/use_case/create_problem_use_case.dart
  lib/create/presentation/screen/test_screen.dart
Labels: feat

#31 feat/로그인,회원가입 Supabase 연동
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/presentation/sign_in/controller/sign_in_action.dart
  lib/auth/presentation/sign_in/controller/sign_in_state.dart
  lib/auth/presentation/sign_in/controller/sign_in_view_model.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen_root.dart
  lib/auth/presentation/sign_up/controller/sign_up_action.dart
  lib/auth/presentation/sign_up/controller/sign_up_state.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/password_sign_up_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_complete_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen_root.dart
  lib/auth/sign_in/controller/sign_in_view_model.dart
  lib/auth/sign_up/controller/sign_up_view_model.dart
  lib/core/di/providers.dart
  lib/core/exception/app_exception.dart
  lib/core/routing/router.dart
  lib/main.dart
  pubspec.yaml
Labels: feat

#32 feat/템플릿 설정 단계(문제 만들기 step 3/5) #20
  lib/core/constants/ai_constant.dart
  lib/core/constants/prompt.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/core/style/app_color.dart
  lib/create/presentation/create_problem/controller/create_problem_action.dart
  lib/create/presentation/create_problem/controller/create_problem_event.dart
  lib/create/presentation/create_problem/controller/create_problem_state.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/screen/test_screen.dart
Labels: feat

#29 feat/텍스트 or 이미지 or pdf를 넣는 screen 구현(문제 만들기 step 2/5)
  lib/core/di/providers.dart
  lib/core/enum/allowed_extension_type.dart
  lib/core/exception/app_exception.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/create/data/data_source/file_picker_data_source.dart
  lib/create/data/data_source/file_picker_data_source_impl.dart
  lib/create/data/dto/pick_file_dto.dart
  lib/create/data/mapper/pick_file_mapper.dart
  lib/create/data/repository/file_picker_repository_impl.dart
  lib/create/domain/model/pick_file.dart
  lib/create/domain/model/request/input_content.dart
  lib/create/domain/model/request/message_input.dart
  lib/create/domain/model/request/open_ai_body.dart
  lib/create/domain/repository/file_picker_repository.dart
  lib/create/domain/use_case/image_pick_file_use_case.dart
  lib/create/domain/use_case/pdf_pick_file_use_case.dart
  lib/create/presentation/controller/upload_raw_action.dart
  lib/create/presentation/controller/upload_raw_event.dart
  lib/create/presentation/controller/upload_raw_state.dart
  lib/create/presentation/controller/upload_raw_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/screen/test_screen.dart
  lib/create/presentation/screen/upload_raw_screen.dart
  lib/create/presentation/screen/upload_raw_screen_root.dart
  pubspec.yaml
Labels: feat

#37 feat/pdf 컴포넌트화
  lib/core/component/pdf_generator.dart
  pubspec.yaml
Labels: feat

#40 Feat/append table, prompt 저장방식 변경
  lib/core/constants/app_table_name.dart
  lib/core/constants/prompt.dart
Labels: feat

#41 Feat/prompt&pdf view
  lib/core/di/providers.dart
  lib/create/data/data_source/prompt_data_source.dart
  lib/create/data/data_source/prompt_data_source_impl.dart
  lib/create/data/dto/prompt_dto.dart
  lib/create/data/mapper/prompt_mapper.dart
  lib/create/data/repository/prompt_repository_impl.dart
  lib/create/domain/model/prompt.dart
  lib/create/domain/repository/prompt_repository.dart
  lib/create/domain/use_case/get_prompts_use_case.dart
  lib/create/presentation/create_problem/controller/create_problem_action.dart
  lib/create/presentation/create_problem/controller/create_problem_state.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/screen/test_screen.dart
Labels: feat

#44 feat/완료 pdf 보여주기 step 5/5
  lib/core/component/pdf_generator.dart
  lib/core/di/providers.dart
  lib/core/exception/app_exception.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/create/domain/model/response/open_ai_response.dart
  lib/create/domain/use_case/download_pdf_use_case.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_action.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_event.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_state.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_view_model.dart
  lib/create/presentation/pdf_preview/screen/pdf_preview_screen.dart
  lib/create/presentation/pdf_preview/screen/pdf_preview_screen_root.dart
Labels: feat

#43 feat/템플릿 설정 단계(문제 만들기 step 4/5)
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/create/domain/model/response/open_ai_response.dart
  lib/create/presentation/create/controller/upload_raw_action.dart
  lib/create/presentation/create/controller/upload_raw_event.dart
  lib/create/presentation/create/controller/upload_raw_state.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create_template/controller/create_template_action.dart
  lib/create/presentation/create_template/controller/create_template_event.dart
  lib/create/presentation/create_template/controller/create_template_state.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
Labels: feat

#45 Feat/supabase db integration (유저, 팀 데이터 Read)
  lib/core/di/providers.dart
  lib/dashboard/data/data_source/folder_data_source.dart
  lib/dashboard/data/data_source/folder_data_source_impl.dart
  lib/dashboard/data/data_source/login_user_data_source.dart
  lib/dashboard/data/data_source/login_user_data_source_impl.dart
  lib/dashboard/data/data_source/team_data_source.dart
  lib/dashboard/data/data_source/team_data_source_impl.dart
  lib/dashboard/data/data_source/user_profile_data_source.dart
  lib/dashboard/data/data_source/user_profile_data_source_impl.dart
  lib/dashboard/data/data_source/workbook_data_source.dart
  lib/dashboard/data/data_source/workbook_data_source_impl.dart
  lib/dashboard/data/dto/folder_dto.dart
  lib/dashboard/data/dto/team_dto.dart
  lib/dashboard/data/dto/user_profile_dto.dart
  lib/dashboard/data/dto/workbook_dto.dart
  lib/dashboard/data/mapper/team_mapper.dart
  lib/dashboard/data/mapper/user_profile_mapper.dart
  lib/dashboard/data/repository/login_user_repository_impl.dart
  lib/dashboard/data/repository/team_repository_impl.dart
  lib/dashboard/data/repository/user_profile_repository_impl.dart
  lib/dashboard/domain/model/folder.dart
  lib/dashboard/domain/model/login_user.dart
  lib/dashboard/domain/model/team.dart
  lib/dashboard/domain/model/user_profile.dart
  lib/dashboard/domain/model/workbook.dart
  lib/dashboard/domain/repository/login_user_repository.dart
  lib/dashboard/domain/repository/team_repository.dart
  lib/dashboard/domain/repository/user_profile_repository.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/dashboard_view_model.dart
Labels: feat

#51 Feat/supabase db integration v2
  .gitignore
  lib/core/di/providers.dart
  lib/core/state/current_team_id_state.dart
  lib/dashboard/data/data_source/team_data_source.dart
  lib/dashboard/data/data_source/team_data_source_impl.dart
  lib/dashboard/data/data_source/user_profile_data_source.dart
  lib/dashboard/data/data_source/user_profile_data_source_impl.dart
  lib/dashboard/data/dto/workbook_dto.dart
  lib/dashboard/data/mapper/folder_mapper.dart
  lib/dashboard/data/mapper/workbook_mapper.dart
  lib/dashboard/data/repository/folder_repository_impl.dart
  lib/dashboard/data/repository/workbook_repository_impl.dart
  lib/dashboard/domain/repository/folder_repository.dart
  lib/dashboard/domain/repository/workbook_repository.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/dashboard_view_model.dart
Labels: feat

#50 feat/회원가입-이메일 OTP 인증 구현
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/presentation/sign_up/controller/sign_up_action.dart
  lib/auth/presentation/sign_up/controller/sign_up_state.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen_root.dart
  lib/core/component/base_text_field.dart
  lib/core/exception/app_exception.dart
Labels: feat

#52 feat/생성단계 전체 리팩토링
  assets/fonts/NanumGothicLight.ttf
  lib/core/component/pdf_generator.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/create/data/mapper/prompt_mapper.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create_problem/controller/create_problem_action.dart
  lib/create/presentation/create_problem/controller/create_problem_event.dart
  lib/create/presentation/create_problem/controller/create_problem_state.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/create_template/controller/create_template_event.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  pubspec.yaml
Labels: refactor

#54 style/컬러칩, 폰트 선언, 등록
  assets/fonts/Pretendard-Bold.ttf
  assets/fonts/Pretendard-Medium.ttf
  assets/fonts/Pretendard-Regular.ttf
  lib/core/style/app_color.dart
  lib/core/style/app_text_style.dart
  pubspec.yaml
Labels: style

#56 style/pdf_generator 한글폰트 적용, 나눔고딕 폰트 제거
  assets/fonts/NanumGothicLight.ttf
  lib/core/component/pdf_generator.dart
  pubspec.yaml
Labels: style

#59 feat/AI 파트 공통으로 사용되는 위젯 구현
  lib/core/style/app_color.dart
  lib/create/presentation/base/layout/ai_base_layout.dart
  lib/create/presentation/base/widgets/ai_base_container.dart
  lib/create/presentation/base/widgets/bottom_navigate_button.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
Labels: feat

#62 feat/문제 생성 1,2단계 디자인 작업
  lib/core/component/base_app_button.dart
  lib/core/enum/allowed_extension_type.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/style/app_color.dart
  lib/create/data/data_source/file_picker_data_source.dart
  lib/create/data/data_source/file_picker_data_source_impl.dart
  lib/create/data/repository/file_picker_repository_impl.dart
  lib/create/domain/model/create_workbook_params.dart
  lib/create/domain/repository/file_picker_repository.dart
  lib/create/domain/use_case/image_pick_file_use_case.dart
  lib/create/domain/use_case/pdf_pick_file_use_case.dart
  lib/create/presentation/base/layout/ai_base_layout.dart
  lib/create/presentation/base/widgets/ai_base_container.dart
  lib/create/presentation/base/widgets/ai_error_view.dart
  lib/create/presentation/base/widgets/ai_loading_view.dart
  lib/create/presentation/base/widgets/bottom_navigate_button.dart
  lib/create/presentation/create/controller/upload_raw_state.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create/widgets/upload_input_file.dart
  lib/create/presentation/create/widgets/upload_input_image.dart
  lib/create/presentation/create/widgets/upload_input_text.dart
  lib/create/presentation/create/widgets/upload_raw_text_field.dart
  lib/create/presentation/create_problem/controller/create_problem_event.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/create/presentation/pdf_preview/screen/pdf_preview_screen.dart
  pubspec.yaml
Labels: feat, refactor

#63 Feat/FolderScreen추가 및 리스트 정렬, 간단한 UI 추가
  lib/core/di/providers.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/core/state/current_folder_id_state.dart
  lib/core/state/workbook_sort_option_state.dart
  lib/dashboard/data/data_source/workbook_data_source_impl.dart
  lib/dashboard/data/dto/workbook_dto.dart
  lib/dashboard/data/mapper/workbook_mapper.dart
  lib/dashboard/domain/model/workbook.dart
  lib/dashboard/presentation/component/button_widget.dart
  lib/dashboard/presentation/component/folder_list_widget.dart
  lib/dashboard/presentation/component/team_list_widget.dart
  lib/dashboard/presentation/component/workbook_grid_item.dart
  lib/dashboard/presentation/component/workbook_list_item.dart
  lib/dashboard/presentation/component/workbook_sort_dropdown_widget.dart
  lib/dashboard/presentation/controller/dashboard_state.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/deleted_files/deleted_files_screen.dart
  lib/dashboard/presentation/folder/controller/folder_state.dart
  lib/dashboard/presentation/folder/controller/folder_view_model.dart
  lib/dashboard/presentation/folder/folder_screen.dart
  lib/dashboard/presentation/home/home_screen.dart
  lib/dashboard/presentation/my_files/my_files_screen.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_state.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_view_model.dart
  lib/dashboard/presentation/recent_files/recent_files_screen.dart
  lib/main.dart
  pubspec.yaml
Labels: feat, refactor

#65 feat/로그인, 회원가입 UI 적용(~비밀번호)
  assets/images/mongo_ai_logo.png
  lib/auth/data/data_source/temp_storage_data_source.dart
  lib/auth/data/data_source/temp_storage_data_source_impl.dart
  lib/auth/data/dto/temp_user_dto.dart
  lib/auth/data/mapper/retrieve/temp_user_mapper.dart
  lib/auth/data/mapper/store/temp_user_store_mapper.dart
  lib/auth/data/repository/temp_storage_repository_impl.dart
  lib/auth/domain/model/temp_user.dart
  lib/auth/domain/repository/temp_storage_repository.dart
  lib/auth/presentation/check_otp/controller/check_otp_action.dart
  lib/auth/presentation/check_otp/controller/check_otp_event.dart
  lib/auth/presentation/check_otp/controller/check_otp_state.dart
  lib/auth/presentation/check_otp/controller/check_otp_view_model.dart
  lib/auth/presentation/check_otp/screen/check_otp_screen.dart
  lib/auth/presentation/check_otp/screen/check_top_screen_root.dart
  lib/auth/presentation/sign_in/controller/sign_in_action.dart
  lib/auth/presentation/sign_in/controller/sign_in_state.dart
  lib/auth/presentation/sign_in/controller/sign_in_view_model.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen.dart
  lib/auth/presentation/sign_up/controller/sign_up_event.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen_root.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_action.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_event.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_state.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_view_model.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen_root.dart
  lib/core/component/auth_header_widget.dart
  lib/core/di/providers.dart
  lib/core/exception/app_exception.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
Labels: feat

#68 feat/문제 생성 3단계 디자인 수정
  lib/create/presentation/create_template/controller/create_template_action.dart
  lib/create/presentation/create_template/controller/create_template_state.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/create/presentation/create_template/widget/create_problem_list_widget.dart
  lib/create/presentation/create_template/widget/create_problem_order_setting_box.dart
  lib/create/presentation/create_template/widget/pdf_template_layer_selector.dart
  lib/create/presentation/create_template/widget/problem_card_widget.dart
Labels: feat, refactor

#69 feat/문제 생성 1,2단계 리팩토링
  lib/core/constants/ai_constant.dart
  lib/core/routing/router.dart
  lib/core/style/app_color.dart
  lib/create/presentation/create/controller/upload_raw_action.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create/widgets/upload_input_file.dart
  lib/create/presentation/create/widgets/upload_input_image.dart
  lib/create/presentation/create/widgets/upload_input_text.dart
  lib/create/presentation/create/widgets/upload_raw_text_field.dart
  lib/create/presentation/create/widgets/upload_tip_box.dart
  lib/create/presentation/create_problem/controller/create_problem_action.dart
  lib/create/presentation/create_problem/controller/create_problem_event.dart
  lib/create/presentation/create_problem/controller/create_problem_state.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/main.dart
Labels: refactor

#70 Feat/그리드뷰 및 bookmark 필터링 추가, UI 수정
  lib/core/enum/workbook_sort_option.dart
  lib/core/state/dashboard_path_state.dart
  lib/core/state/selected_workbook_state.dart
  lib/core/state/workbook_filter_state.dart
  lib/core/state/workbook_sort_option_state.dart
  lib/dashboard/domain/use_case/select_workbook_use_case.dart
  lib/dashboard/presentation/component/folder_list_widget.dart
  lib/dashboard/presentation/component/path_widget.dart
  lib/dashboard/presentation/component/team_list_widget.dart
  lib/dashboard/presentation/component/workbook_filter_bookmark_widget.dart
  lib/dashboard/presentation/component/workbook_filter_sort_widget.dart
  lib/dashboard/presentation/component/workbook_filter_tab_bar.dart
  lib/dashboard/presentation/component/workbook_grid_item.dart
  lib/dashboard/presentation/component/workbook_list_item.dart
  lib/dashboard/presentation/component/workbook_sort_dropdown_widget.dart
  lib/dashboard/presentation/controller/dashboard_state.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/folder/controller/folder_state.dart
  lib/dashboard/presentation/folder/controller/folder_view_model.dart
  lib/dashboard/presentation/folder/folder_screen.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_state.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_view_model.dart
  lib/dashboard/presentation/recent_files/recent_files_screen.dart
  pubspec.yaml
Labels: feat

#72 feat/회원가입 구현(otp~회원가입 완료)
  assets/lottie/check_lottie.json
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/data_source/temp_storage_data_source.dart
  lib/auth/data/data_source/temp_storage_data_source_impl.dart
  lib/auth/data/dto/temp_user_dto.dart
  lib/auth/data/mapper/retrieve/temp_user_mapper.dart
  lib/auth/data/mapper/store/temp_user_store_mapper.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/data/repository/temp_storage_repository_impl.dart
  lib/auth/domain/model/password_criteria.dart
  lib/auth/domain/model/temp_user.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/domain/repository/temp_storage_repository.dart
  lib/auth/presentation/check_otp/controller/check_otp_action.dart
  lib/auth/presentation/check_otp/controller/check_otp_event.dart
  lib/auth/presentation/check_otp/controller/check_otp_state.dart
  lib/auth/presentation/check_otp/controller/check_otp_view_model.dart
  lib/auth/presentation/check_otp/screen/check_otp_screen.dart
  lib/auth/presentation/check_otp/screen/check_otp_screen_root.dart
  lib/auth/presentation/sign_in/controller/sign_in_view_model.dart
  lib/auth/presentation/sign_up/controller/sign_up_action.dart
  lib/auth/presentation/sign_up/controller/sign_up_event.dart
  lib/auth/presentation/sign_up/controller/sign_up_state.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen_root.dart
  lib/auth/presentation/sign_up_complete/controller/sign_up_complete_action.dart
  lib/auth/presentation/sign_up_complete/screen/sign_up_complete_screen.dart
  lib/auth/presentation/sign_up_complete/screen/sign_up_complete_screen_root.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_action.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_event.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_state.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_view_model.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen_root.dart
  lib/core/component/auth_feature_item_widget.dart
  lib/core/component/password_requirement_widget.dart
  lib/core/di/providers.dart
  lib/core/exception/app_exception.dart
  lib/core/extension/int_extension.dart
  lib/core/extension/string_extension.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  pubspec.yaml
Labels: feat

#77 fix/selected workbook state 수정
  lib/core/state/selected_workbook_state.dart
  lib/dashboard/presentation/component/workbook_grid_item.dart
  lib/dashboard/presentation/component/workbook_list_item.dart
Labels: fix

#78 feat/auth - 최초 진입 시 team 선택, 이에 따른 리다이렉트 조건 추가
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/presentation/check_otp/controller/check_otp_view_model.dart
  lib/auth/presentation/check_otp/screen/check_otp_screen.dart
  lib/auth/presentation/check_otp/screen/check_otp_screen_root.dart
  lib/auth/presentation/components/auth_feature_item_widget.dart
  lib/auth/presentation/components/auth_header_widget.dart
  lib/auth/presentation/components/select_team_info_panel.dart
  lib/auth/presentation/components/select_team_main_content_panel.dart
  lib/auth/presentation/components/select_team_small_screen_info_summary.dart
  lib/auth/presentation/select_team/controller/select_team_action.dart
  lib/auth/presentation/select_team/controller/select_team_event.dart
  lib/auth/presentation/select_team/controller/select_team_state.dart
  lib/auth/presentation/select_team/controller/select_team_view_model.dart
  lib/auth/presentation/select_team/screen/select_team_screen.dart
  lib/auth/presentation/select_team/screen/select_team_screen_root.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen.dart
  lib/auth/presentation/sign_up_complete/screen/sign_up_complete_screen.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen.dart
  lib/core/di/providers.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/dashboard/data/data_source/team_data_source.dart
  lib/dashboard/data/data_source/team_data_source_impl.dart
  lib/dashboard/data/repository/team_repository_impl.dart
  lib/dashboard/domain/repository/team_repository.dart
Labels: feat

#86 Feat/휴지통 및 Workbook 삭제, Path UI 오류 수정
  lib/core/di/providers.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/core/state/current_team_id_state.dart
  lib/core/state/dashboard_path_state.dart
  lib/core/state/deleted_workbook_state.dart
  lib/dashboard/domain/use_case/delete_workbook_use_case.dart
  lib/dashboard/domain/use_case/update_workbook_use_case.dart
  lib/dashboard/presentation/component/deleted_grid_item.dart
  lib/dashboard/presentation/component/deleted_list_item.dart
  lib/dashboard/presentation/component/path_widget.dart
  lib/dashboard/presentation/component/workbook_grid_item.dart
  lib/dashboard/presentation/component/workbook_list_item.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/deleted_files/controller/deleted_files_state.dart
  lib/dashboard/presentation/deleted_files/controller/deleted_files_view_model.dart
  lib/dashboard/presentation/deleted_files/deleted_files_screen.dart
  lib/dashboard/presentation/folder/controller/folder_view_model.dart
  lib/dashboard/presentation/folder/folder_screen.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_view_model.dart
  lib/dashboard/presentation/recent_files/recent_files_screen.dart
Labels: feat, fix

#84 feat/ 문제 생성 1,2단계 추가 구현
  lib/core/constants/ai_constant.dart
  lib/core/debounce/debounce.dart
  lib/core/routing/router.dart
  lib/core/state/selected_workbook_state.dart
  lib/create/data/dto/request/open_ai_body_dto.dart
  lib/create/data/mapper/request/open_ai_body_mapper.dart
  lib/create/domain/model/create_workbook_params.dart
  lib/create/domain/model/pick_file.dart
  lib/create/domain/model/request/open_ai_body.dart
  lib/create/presentation/create/controller/upload_raw_action.dart
  lib/create/presentation/create/controller/upload_raw_state.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create/widgets/upload_input_file.dart
  lib/create/presentation/create/widgets/upload_input_image.dart
  lib/create/presentation/create_problem/controller/create_problem_state.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/dashboard/presentation/component/workbook_grid_item.dart
  lib/dashboard/presentation/component/workbook_list_item.dart
  pubspec.yaml
Labels: refactor

#85 feat/문제 생성 4단계 디자인 수정 및 기능 구체화
  lib/core/component/pdf_generator.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/create/presentation/create_complete/controller/create_complete_action.dart
  lib/create/presentation/create_complete/controller/create_complete_event.dart
  lib/create/presentation/create_complete/controller/create_complete_state.dart
  lib/create/presentation/create_complete/controller/create_complete_view_model.dart
  lib/create/presentation/create_complete/controller/problem_editor_state.dart
  lib/create/presentation/create_complete/screen/create_complete_screen.dart
  lib/create/presentation/create_complete/screen/create_complete_screen_root.dart
  lib/create/presentation/create_complete/widget/pdf_preview_dialog.dart
  lib/create/presentation/create_complete/widget/problem_content_editor.dart
  lib/create/presentation/create_complete/widget/problem_options_editor.dart
  lib/create/presentation/create_complete/widget/problem_preview_widget.dart
  lib/create/presentation/create_complete/widget/problem_question_editor.dart
  lib/create/presentation/create_complete/widget/problem_title_editor.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_action.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_event.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_state.dart
  lib/create/presentation/pdf_preview/controller/pdf_preview_view_model.dart
  lib/create/presentation/pdf_preview/screen/pdf_preview_screen.dart
  lib/create/presentation/pdf_preview/screen/pdf_preview_screen_root.dart
Labels: feat

#87 feat/google OAuth 구성, auth 단 리팩토링
  .gitignore
  assets/images/google_logo.png
  firebase.json
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/domain/model/auth_state_change.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/presentation/sign_in/controller/sign_in_action.dart
  lib/auth/presentation/sign_in/controller/sign_in_event.dart
  lib/auth/presentation/sign_in/controller/sign_in_view_model.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen_root.dart
  lib/auth/presentation/sign_up/controller/sign_up_action.dart
  lib/auth/presentation/sign_up/controller/sign_up_state.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/password_sign_up_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_complete_screen.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen_root.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_view_model.dart
  lib/main.dart
  pubspec.yaml
Labels: feat

#98 feat/my_profile 화면 구현
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/presentation/select_team/controller/select_team_view_model.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/dashboard/data/data_source/user_profile_data_source.dart
  lib/dashboard/data/data_source/user_profile_data_source_impl.dart
  lib/dashboard/data/repository/user_profile_repository_impl.dart
  lib/dashboard/domain/repository/user_profile_repository.dart
  lib/dashboard/presentation/component/delete_account_alert_dialog.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/my_profile/controller/my_profile_action.dart
  lib/dashboard/presentation/my_profile/controller/my_profile_event.dart
  lib/dashboard/presentation/my_profile/controller/my_profile_state.dart
  lib/dashboard/presentation/my_profile/controller/my_profile_view_model.dart
  lib/dashboard/presentation/my_profile/screen/my_profile_screen.dart
  lib/dashboard/presentation/my_profile/screen/my_profile_screen_root.dart
Labels: feat

#99 feat/ 문제집 생성 및 저장 구현
  lib/core/di/providers.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/create/data/data_source/problem_data_source.dart
  lib/create/data/data_source/problem_data_source_impl.dart
  lib/create/data/dto/problem_dto.dart
  lib/create/data/mapper/problem_mapper.dart
  lib/create/data/repository/problem_repository_impl.dart
  lib/create/domain/model/create_template_params.dart
  lib/create/domain/model/create_workbook_params.dart
  lib/create/domain/repository/problem_repository.dart
  lib/create/presentation/base/layout/ai_base_layout.dart
  lib/create/presentation/create_complete/controller/create_complete_action.dart
  lib/create/presentation/create_complete/controller/create_complete_state.dart
  lib/create/presentation/create_complete/controller/create_complete_view_model.dart
  lib/create/presentation/create_complete/controller/problem_editor_state.dart
  lib/create/presentation/create_complete/screen/create_complete_screen_root.dart
  lib/create/presentation/create_complete/widget/problem_preview_widget.dart
  lib/create/presentation/create_problem/controller/create_problem_event.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_template/controller/create_template_action.dart
  lib/create/presentation/create_template/controller/create_template_state.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/create/presentation/create_template/widget/create_problem_list_widget.dart
  lib/create/presentation/create_template/widget/create_problem_order_setting_box.dart
  lib/create/presentation/create_template/widget/problem_card_widget.dart
Labels: feat

#106 refactor/login flow 로직 분리, 트랜지션 등 리팩토링 + 팀 선택 정보 저장 및 불러오기
  .gitignore
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/presentation/select_team/controller/select_team_view_model.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen.dart
  lib/core/state/current_team_id_state.dart
  lib/core/utils/validators.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  pubspec.yaml
  test/auth/domain/repository/auth_repository_test.dart
  test/widget_test.dart
Labels: feat, refactor

#96 feat/결제페이지 디자인, 뷰 생성
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/landing/domain/enum/landing_header_menu_type.dart
  lib/landing/presentation/components/faq_item.dart
  lib/landing/presentation/components/landing_footer.dart
  lib/landing/presentation/components/landing_header_navigation_item.dart
  lib/landing/presentation/components/price_card.dart
  lib/landing/presentation/landing_page/screen/landing_page_screen.dart
  lib/landing/presentation/landing_page/screen/landing_page_screen_root.dart
  lib/landing/presentation/landing_shell/controller/landing_shell_action.dart
  lib/landing/presentation/landing_shell/controller/landing_shell_state.dart
  lib/landing/presentation/landing_shell/controller/landing_shell_view_model.dart
  lib/landing/presentation/landing_shell/screen/landing_header.dart
  lib/landing/presentation/landing_shell/screen/landing_shell_screen.dart
  lib/landing/presentation/landing_shell/screen/landing_shell_screen_root.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_action.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_event.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_view_model.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen_root.dart
Labels: feat

#109 feat/랜딩페이지 구현
  lib/core/component/base_app_button.dart
  lib/core/debounce/debounce.dart
  lib/core/routing/router.dart
  lib/core/style/app_color.dart
  lib/core/style/app_text_style.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/landing/presentation/components/landing_create_stage_card.dart
  lib/landing/presentation/components/landing_feature_card.dart
  lib/landing/presentation/components/landing_footer.dart
  lib/landing/presentation/components/landing_introduce_card.dart
  lib/landing/presentation/landing_page/controller/landing_page_action.dart
  lib/landing/presentation/landing_page/screen/landing_page_screen.dart
  lib/landing/presentation/landing_page/screen/landing_page_screen_root.dart
  lib/landing/presentation/landing_page/screen/landing_page_view/landing_create_problem_view.dart
  lib/landing/presentation/landing_page/screen/landing_page_view/landing_introduce_view.dart
  lib/landing/presentation/landing_page/screen/landing_page_view/landing_key_features_view.dart
  lib/landing/presentation/landing_page/screen/landing_page_view/landing_start_view.dart
  lib/landing/presentation/landing_shell/controller/landing_shell_action.dart
  lib/landing/presentation/landing_shell/controller/landing_shell_view_model.dart
  lib/landing/presentation/landing_shell/screen/landing_header.dart
  lib/main.dart
Labels: feat

#112 feat/실제 웹 배포
  .github/workflows/web-deploy.yml
  .gitignore
  lib/auth/presentation/components/auth_header_widget.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/firebase_options.dart
  pubspec.yaml
  web/favicon.png
  web/icons/Icon-192.png
  web/icons/Icon-512.png
  web/icons/Icon-maskable-192.png
  web/icons/Icon-maskable-512.png
  web/index.html
  web/manifest.json
Labels: feat

#117 Feat/dashboard 드래그 기능 추가, 사이드바 드래그앤 드롭 추가
  lib/core/di/providers.dart
  lib/dashboard/data/data_source/workbook_data_source.dart
  lib/dashboard/data/data_source/workbook_data_source_impl.dart
  lib/dashboard/data/repository/workbook_repository_impl.dart
  lib/dashboard/domain/repository/workbook_repository.dart
  lib/dashboard/domain/use_case/bookmark_workbook_list_use_case.dart
  lib/dashboard/domain/use_case/change_folder_workbook_list_use_case.dart
  lib/dashboard/domain/use_case/move_trash_workbook_list_use_case.dart
  lib/dashboard/domain/use_case/move_trash_workbook_use_case.dart
  lib/dashboard/presentation/component/folder_list_widget.dart
  lib/dashboard/presentation/component/merge_button_widget.dart
  lib/dashboard/presentation/component/select_mode_button_widget.dart
  lib/dashboard/presentation/component/workbook_view/base_selectable_view.dart
  lib/dashboard/presentation/component/workbook_view/workbook_grid_item.dart
  lib/dashboard/presentation/component/workbook_view/workbook_grid_view.dart
  lib/dashboard/presentation/component/workbook_view/workbook_list_item.dart
  lib/dashboard/presentation/component/workbook_view/workbook_list_view.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/folder/controller/folder_view_model.dart
  lib/dashboard/presentation/folder/folder_screen.dart
  lib/dashboard/presentation/my_files/controller/my_files_view_model.dart
  lib/dashboard/presentation/my_files/my_files_screen.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_view_model.dart
  lib/dashboard/presentation/recent_files/recent_files_screen.dart
Labels: feat

#121 Feat/휴지통 드래그, 다중 영구삭제, 복원 구현.
  lib/core/di/providers.dart
  lib/core/state/deleted_workbook_state.dart
  lib/dashboard/data/repository/workbook_repository_impl.dart
  lib/dashboard/domain/repository/workbook_repository.dart
  lib/dashboard/domain/use_case/delete_workbook_list_use_case.dart
  lib/dashboard/domain/use_case/restore_workbook_list_use_case.dart
  lib/dashboard/presentation/component/button/button_widget.dart
  lib/dashboard/presentation/component/button/clean_trash_button.dart
  lib/dashboard/presentation/component/button/delete_mode_button_widget.dart
  lib/dashboard/presentation/component/button/merge_button_widget.dart
  lib/dashboard/presentation/component/button/restore_button_widget.dart
  lib/dashboard/presentation/component/button/select_mode_button_widget.dart
  lib/dashboard/presentation/component/delete_view/deleted_grid_item.dart
  lib/dashboard/presentation/component/delete_view/deleted_grid_view.dart
  lib/dashboard/presentation/component/delete_view/deleted_list_item.dart
  lib/dashboard/presentation/component/delete_view/deleted_list_view.dart
  lib/dashboard/presentation/component/delete_workbook_alert_dialog.dart
  lib/dashboard/presentation/component/deleted_files_info_widget.dart
  lib/dashboard/presentation/component/team_list_widget.dart
  lib/dashboard/presentation/component/workbook_view/deleted_grid_item.dart
  lib/dashboard/presentation/component/workbook_view/deleted_grid_view.dart
  lib/dashboard/presentation/component/workbook_view/deleted_list_view.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/deleted_files/controller/deleted_files_view_model.dart
  lib/dashboard/presentation/deleted_files/deleted_files_screen.dart
Labels: feat

#114 feat/문제 생성 3단계 문제 재생성 기능 추가
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/create/domain/model/create_complete_params.dart
  lib/create/domain/model/create_template_params.dart
  lib/create/presentation/base/widgets/ai_loading_view.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create_complete/controller/create_complete_view_model.dart
  lib/create/presentation/create_complete/screen/create_complete_screen_root.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/create_template/controller/create_template_action.dart
  lib/create/presentation/create_template/controller/create_template_state.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/create/presentation/create_template/widget/create_problem_list_widget.dart
  lib/create/presentation/create_template/widget/create_problem_order_setting_box.dart
  lib/create/presentation/create_template/widget/problem_card_widget.dart
  lib/create/presentation/create_template/widget/problem_detail_dialog.dart
  pubspec.yaml
Labels: feat

#124 feat/개인정보처리방침 구현, 프로필 이름 안바뀌는 문제 해결, README.md 재작성
  README.md
  lib/auth/presentation/sign_up_password/controller/sign_up_password_action.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen_root.dart
  lib/core/constants/app_table_name.dart
  lib/core/di/providers.dart
  lib/core/exception/app_exception.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/core/routing/routes.dart
  lib/landing/data/data_source/privacy_policies_data_source.dart
  lib/landing/data/data_source/privacy_policies_data_source_impl.dart
  lib/landing/data/dto/privacy_policies_dto.dart
  lib/landing/data/mapper/privacy_policies_mapper.dart
  lib/landing/data/repository/privacy_policies_repository_impl.dart
  lib/landing/domain/model/privacy_policies.dart
  lib/landing/domain/repository/privacy_policies_repository.dart
  lib/landing/presentation/components/landing_footer.dart
  lib/landing/presentation/components/landing_footer_link_button.dart
  lib/landing/presentation/components/landing_footer_social_icon.dart
  lib/landing/presentation/landing_page/controller/landing_page_action.dart
  lib/landing/presentation/landing_page/screen/landing_page_screen.dart
  lib/landing/presentation/landing_page/screen/landing_page_view/landing_start_view.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_action.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen_root.dart
  lib/landing/presentation/privacy_policies/controller/privacy_policies_state.dart
  lib/landing/presentation/privacy_policies/controller/privacy_policies_view_model.dart
  lib/landing/presentation/privacy_policies/screen/privacy_policies_screen.dart
  lib/landing/presentation/privacy_policies/screen/privacy_policies_screen_root.dart
Labels: feat

#127 fix, feat/로그인 유저 팀 선택 로직 수정, 팀 추가 선택 기능 추가
  lib/auth/data/data_source/auth_data_source.dart
  lib/auth/data/data_source/auth_data_source_impl.dart
  lib/auth/data/repository/auth_repository_impl.dart
  lib/auth/domain/repository/auth_repository.dart
  lib/auth/presentation/components/select_team_main_content_panel.dart
  lib/auth/presentation/select_team/controller/select_team_action.dart
  lib/auth/presentation/select_team/controller/select_team_event.dart
  lib/auth/presentation/select_team/controller/select_team_state.dart
  lib/auth/presentation/select_team/controller/select_team_view_model.dart
  lib/auth/presentation/select_team/screen/select_team_screen_root.dart
  lib/core/routing/redirect.dart
  lib/core/routing/router.dart
  lib/dashboard/data/data_source/team_data_source.dart
  lib/dashboard/data/data_source/team_data_source_impl.dart
  lib/dashboard/data/repository/team_repository_impl.dart
  lib/dashboard/domain/repository/team_repository.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  test/auth/domain/repository/auth_repository_test.dart
Labels: feat, fix

#125 refactor/riverpod listen 활용
  lib/auth/presentation/check_otp/controller/check_otp_event.dart
  lib/auth/presentation/check_otp/controller/check_otp_view_model.dart
  lib/auth/presentation/check_otp/screen/check_otp_screen_root.dart
  lib/auth/presentation/select_team/controller/select_team_event.dart
  lib/auth/presentation/select_team/controller/select_team_view_model.dart
  lib/auth/presentation/select_team/screen/select_team_screen_root.dart
  lib/auth/presentation/sign_in/controller/sign_in_event.dart
  lib/auth/presentation/sign_in/controller/sign_in_view_model.dart
  lib/auth/presentation/sign_in/screen/sign_in_screen_root.dart
  lib/auth/presentation/sign_up/controller/sign_up_event.dart
  lib/auth/presentation/sign_up/controller/sign_up_view_model.dart
  lib/auth/presentation/sign_up/screen/sign_up_screen_root.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_event.dart
  lib/auth/presentation/sign_up_password/controller/sign_up_password_view_model.dart
  lib/auth/presentation/sign_up_password/screen/sign_up_password_screen_root.dart
  lib/core/event/app_event.dart
  lib/core/event/app_event_provider.dart
  lib/core/event/key/event_key.dart
  lib/core/event/key/event_key_state.dart
  lib/core/extension/ref_extension.dart
  lib/core/routing/router.dart
  lib/core/state/current_folder_id_state.dart
  lib/core/utils/app_dialog.dart
  lib/core/utils/input_converter.dart
  lib/create/data/dto/request/message_input_dto.dart
  lib/create/presentation/create/controller/upload_raw_event.dart
  lib/create/presentation/create/controller/upload_raw_view_model.dart
  lib/create/presentation/create/screen/upload_raw_screen_root.dart
  lib/create/presentation/create_complete/controller/create_complete_event.dart
  lib/create/presentation/create_complete/controller/create_complete_view_model.dart
  lib/create/presentation/create_complete/screen/create_complete_screen_root.dart
  lib/create/presentation/create_problem/controller/create_problem_event.dart
  lib/create/presentation/create_problem/controller/create_problem_view_model.dart
  lib/create/presentation/create_problem/screen/create_problem_screen_root.dart
  lib/create/presentation/create_template/controller/create_template_event.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/create/presentation/create_template/screen/create_template_screen_root.dart
  lib/dashboard/presentation/controller/dashboard_state.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/my_profile/controller/my_profile_event.dart
  lib/dashboard/presentation/my_profile/controller/my_profile_view_model.dart
  lib/dashboard/presentation/my_profile/screen/my_profile_screen_root.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_event.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_view_model.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen_root.dart
  lib/main.dart
  test/auth/domain/repository/auth_repository_test.dart
Labels: refactor

#130 fix/유저가 팀에 속해있는지 여부를 알 수 있는 메서드 호출 추가
  lib/auth/presentation/select_team/screen/select_team_screen_root.dart
Labels: fix

#132 feat/결제 기능 구현 및 편집모드 고도화
  lib/core/di/providers.dart
  lib/core/routing/router.dart
  lib/core/service/portone_payment_service.dart
  lib/core/utils/app_dialog.dart
  lib/create/presentation/create_complete/controller/create_complete_view_model.dart
  lib/create/presentation/create_template/controller/create_template_view_model.dart
  lib/landing/data/data_source/payment_data_source.dart
  lib/landing/data/data_source/payment_data_source_impl.dart
  lib/landing/data/dto/payment_key_response_dto.dart
  lib/landing/data/dto/payment_request_dto.dart
  lib/landing/data/mapper/payment_request_mapper.dart
  lib/landing/data/repository/payment_repository_impl.dart
  lib/landing/domain/model/payment_data.dart
  lib/landing/domain/repository/payment_repository.dart
  lib/landing/presentation/components/price_card.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_event.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_state.dart
  lib/landing/presentation/payment_plans/controller/payment_plans_view_model.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen.dart
  lib/landing/presentation/payment_plans/screen/payment_plans_screen_root.dart
  web/index.html
Labels: feat

#131 Refactor/Dashboard 리팩토링, 스낵바 추가
  lib/core/routing/router.dart
  lib/dashboard/presentation/component/delete_view/deleted_grid_view.dart
  lib/dashboard/presentation/component/delete_view/deleted_list_view.dart
  lib/dashboard/presentation/component/workbook_view/workbook_grid_view.dart
  lib/dashboard/presentation/component/workbook_view/workbook_list_view.dart
  lib/dashboard/presentation/controller/dashboard_view_model.dart
  lib/dashboard/presentation/dashboard_screen.dart
  lib/dashboard/presentation/deleted_files/controller/deleted_files_action.dart
  lib/dashboard/presentation/deleted_files/controller/deleted_files_view_model.dart
  lib/dashboard/presentation/deleted_files/deleted_files_screen.dart
  lib/dashboard/presentation/deleted_files/screen/deleted_files_screen.dart
  lib/dashboard/presentation/deleted_files/screen/deleted_files_screen_root.dart
  lib/dashboard/presentation/folder/controller/folder_action.dart
  lib/dashboard/presentation/folder/controller/folder_view_model.dart
  lib/dashboard/presentation/folder/folder_screen.dart
  lib/dashboard/presentation/folder/screen/folder_screen.dart
  lib/dashboard/presentation/folder/screen/folder_screen_root.dart
  lib/dashboard/presentation/my_files/controller/my_files_action.dart
  lib/dashboard/presentation/my_files/controller/my_files_view_model.dart
  lib/dashboard/presentation/my_files/my_files_screen.dart
  lib/dashboard/presentation/my_files/screen/my_files_screen.dart
  lib/dashboard/presentation/my_files/screen/my_files_screen_root.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_action.dart
  lib/dashboard/presentation/recent_files/controller/recent_files_view_model.dart
  lib/dashboard/presentation/recent_files/recent_files_screen.dart
  lib/dashboard/presentation/recent_files/screen/recent_files_screen.dart
  lib/dashboard/presentation/recent_files/screen/recent_files_screen_root.dart
Labels: feat, refactor
